In [2]:
DATA_PATH = "../data/raw/"
import pandas as pd

In [3]:
orders = pd.read_csv(DATA_PATH + "olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
orders.shape

(99441, 8)

In [5]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [6]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [7]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [8]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [9]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [10]:
orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isna())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [11]:
orders[orders['order_approved_at'].isna()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [12]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [13]:
orders['order_id'].nunique()

99441

In [14]:
len(orders)

99441

## Orders Table - Initial Findings

- The 'orders' table contains one record per order.
- 'order_id' uniquely identifies each order.
- 'customer_id' links orders to customer records.
- 'order_status' describes the order lifecycle.
- The timestamp columns are mappes as string.
- Missing timestamp values are related largely to the order lifecycle.
- A small no. of records contain inconsistent combinations.
- these exceptions will be  investigated and handled during the data-cleaning stage

In [15]:
customers = pd.read_csv(DATA_PATH + 'olist_customers_dataset.csv')

In [16]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [17]:
customers.shape

(99441, 5)

In [18]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [19]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [20]:
customers.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [21]:
customers['customer_id'].nunique()

99441

In [22]:
customers['customer_unique_id'].nunique()

96096

In [23]:
customers.groupby('customer_unique_id')['customer_id'].nunique().value_counts()

customer_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [24]:
customers.duplicated().sum()

np.int64(0)

In [25]:
customers['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

## Customer Table - Findings

- The table contains 99441 customer records.
- 'customer_id' uniquely identifies the customer record used for relational joins.
- 'customer_unique_id' identifies persistent customer across multiple records.
- 96096 unique 'customer_unique_id' .
- multiple c_id records can belong to same 'customer_unique_id'
-  no duplicated row
- no missing/na values
- 27 customer states/regions.
- SP has largest customers number
- 'customer_unique_id' will be used for customer-level behavioral analysis such as RFM and churn.

In [26]:
order_items = pd.read_csv(DATA_PATH + 'olist_order_items_dataset.csv')

In [27]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [28]:
order_items.shape

(112650, 7)

In [29]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [30]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [31]:
order_items.duplicated().sum()

np.int64(0)

In [32]:
order_items['order_id'].nunique()

98666

In [33]:
len(order_items)

112650

In [34]:
order_items['order_item_id'].nunique()

21

In [35]:
order_items.duplicated(subset = ['order_id', 'order_item_id']).sum()

np.int64(0)

In [36]:
items_per_order = (order_items.groupby('order_id').size())
items_per_order.describe()

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64

In [37]:
items_per_order.value_counts().sort_index()

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

## Order Items - Findings

- The 'order_items' table has 112,650 item-level records
-  There are 98,666 unnique orders in it
- one row represents one item within order
- 'order_id' connects order items to the order table
- 'order_item_id' represents the item's sequence within an order rather than a globally unique itemid
- combination of order id and order_item_id is unique.
- no missing/na value.
- no completely duplicated rows
-  approximately 90% of orders represented in table contain exactly one item.
- avg orders contain 1.14 items.
- some orders contain substantially more items, maximum 21 items
- 'price' and 'freight' values will later be used to construct order-level financial metrics.

In [38]:
products = pd.read_csv(DATA_PATH + "olist_products_dataset.csv")

In [39]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [40]:
products.shape

(32951, 9)

In [41]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [42]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [43]:
products.duplicated().sum()

np.int64(0)

In [44]:
products.groupby('product_category_name')['product_id'].nunique()

product_category_name
agro_industria_e_comercio      74
alimentos                      82
alimentos_bebidas             104
artes                          55
artes_e_artesanato             19
                             ...
sinalizacao_e_seguranca        93
tablets_impressao_imagem        9
telefonia                    1134
telefonia_fixa                116
utilidades_domesticas        2335
Name: product_id, Length: 73, dtype: int64

In [45]:
products[products['product_category_name'].isna()][['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN

In [46]:
products[products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
category_translation = pd.read_csv(DATA_PATH + 'product_category_name_translation.csv')

In [48]:
category_translation.head(20)

          product_category_name product_category_name_english
0                  beleza_saude                 health_beauty
1        informatica_acessorios         computers_accessories
2                    automotivo                          auto
3               cama_mesa_banho                bed_bath_table
4              moveis_decoracao               furniture_decor
5                 esporte_lazer                sports_leisure
6                    perfumaria                     perfumery
7         utilidades_domesticas                    housewares
8                     telefonia                     telephony
9            relogios_presentes                 watches_gifts
10            alimentos_bebidas                    food_drink
11                        bebes                          baby
12                    papelaria                    stationery
13     tablets_impressao_imagem        tablets_printing_image
14                   brinquedos                          toys
15               telefonia_fixa               fixed_telephony
16           ferramentas_jardim                  garden_tools
17  fashion_bolsas_e_acessorios      fashion_bags_accessories
18              eletroportateis              small_appliances
19               consoles_games                consoles_games

In [49]:
category_translation.shape

(71, 2)

In [50]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='str')

In [51]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [52]:
category_translation.duplicated().sum()

np.int64(0)

In [53]:
category_translation['product_category_name'].duplicated().sum()

np.int64(0)

In [54]:
category_translation['product_category_name'].nunique()

71

In [55]:
translated_categories = set(category_translation['product_category_name'])
product_categories = set(products['product_category_name'].dropna())
product_categories - translated_categories

{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

## Category_translation findings

- The category translation has 71 category mappings
- It contains two columns: 'product_category_name' and 'product_category_name_english'
- No missing/na() values
- no completely duplicated rows.
- 'product category name' has no duplicate category mappings.
- products table has 73 distinct non-null categories, while the translation table contains 71.
- categories do not have an English translation in the supplied translation table : 'pc_gamer', 'portateis_cozinha_preparandores_de_alimentos'
- These missing will be handled explicitly during the data cleaning / feature-engineering stage rather than doing it here in exploration.

In [56]:
sellers = pd.read_csv(DATA_PATH + "olist_sellers_dataset.csv")

In [57]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [58]:
sellers.shape

(3095, 4)

In [59]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')

In [60]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [61]:
sellers.duplicated().sum()

np.int64(0)

In [62]:
sellers['seller_id'].duplicated().sum()

np.int64(0)

## Sellers Findings

- it has 3095 seller records and 4 columns
- 'seller_id' uniquely identifies a seller record.
- 'seller_id' connects seller info to order_items.
- no missing/na() values
- no completely duplicated rows
- no duplicate 'seller_id' values.
- seller info contains zipcode prefix, city and state.
- seller geography can be used for operational & anomaly analysis

In [63]:
payments = pd.read_csv(DATA_PATH + 'olist_order_payments_dataset.csv')

In [64]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [65]:
payments.shape

(103886, 5)

In [67]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [68]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [69]:
payments.duplicated().sum()

np.int64(0)

In [70]:
payments['order_id'].nunique()

99440

In [71]:
payments['payment_sequential'].nunique()

29

In [72]:
payments['order_id'].nunique()

99440

In [73]:
payments['payment_sequential'].nunique()

29

In [74]:
payments.duplicated(subset=['order_id', 'payment_sequential']).sum()

np.int64(0)

In [75]:
payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [76]:
payments.groupby('order_id').size().describe()

count    99440.000000
mean         1.044710
std          0.381166
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
dtype: float64

In [78]:
multiple_payment_orders = (payments.groupby('order_id').size())
(multiple_payment_orders >1).sum()

np.int64(2961)

In [79]:
multiple_payment_orders[multiple_payment_orders > 1].value_counts().sort_index()

2     2382
3      301
4      108
5       52
6       36
7       28
8       11
9        9
10       5
11       8
12       8
13       3
14       2
15       2
19       2
21       1
22       1
26       1
29       1
Name: count, dtype: int64

## Payments Findings

- The payments table contains 103886 payment records.
- There are 99440 unqiue orders in payments table.
- One row rep. one payment record for an order.
- the combination of 'order_id' and 'payment_sequential' uniquely identifies a payment record.
- there are 29 distinct payment sequence positions.
- credit card is most payment type, followed by boleto, voucher, and debit card.
- 2961 orders have multiple payment records.
- most multi-payment orders contain exactly 2 payment records.
- one order contains 29 payment records.
- payment values must be aggregated at order level before being combined with one-to-many tables to prevent double counting.

In [80]:
reviews = pd.read_csv(DATA_PATH + "olist_order_reviews_dataset.csv")

In [81]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [82]:
reviews.shape

(99224, 7)

In [83]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [84]:
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [85]:
reviews.duplicated().sum()

np.int64(0)

In [89]:
reviews['review_id'].nunique()

98410

In [90]:
reviews['order_id'].nunique()

98673

In [91]:
reviews_per_order = (reviews.groupby('order_id').size())
reviews_per_order.describe()

count    98673.000000
mean         1.005584
std          0.075060
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
dtype: float64

In [92]:
(reviews_per_order > 1).sum()

np.int64(547)

In [93]:
reviews_per_order[reviews_per_order > 1].value_counts().sort_index()

2    543
3      4
Name: count, dtype: int64

In [94]:
reviews['review_score'].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [95]:
reviews[reviews['review_id'].duplicated(keep=False)].sort_values('review_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
...,...,...,...,...,...,...,...
31120,fe5c833752953fed3209646f1f63b53c,4863e15fa53273cc7219c58f5ffda4fb,1,NaN,"Comprei dois produtos e ambos, mesmo enviados ...",2018-02-28 00:00:00,2018-02-28 13:57:52
7870,ff2fc9e68f8aabfbe18d710b83aabd30,2da58e0a7dcfa4ce1e00fad9d03ca3b5,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
82521,ff2fc9e68f8aabfbe18d710b83aabd30,1078d496cc6ab9a8e6f2be77abf5091b,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
73951,ffb8cff872a625632ac983eb1f88843c,c44883fc2529b4aa03ca90e7e09d95b6,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07

In [96]:
reviews['review_id'].value_counts().value_counts().sort_index()

count
1    97621
2      764
3       25
Name: count, dtype: int64

In [97]:
(reviews.groupby('review_id')['order_id'].nunique().value_counts().sort_index())

order_id
1    97621
2      764
3       25
Name: count, dtype: int64

## Reviews Findings

- It has 99224 review records.
- 98410 unique reviewid
- reviewid is not unique in supplied dataset
- 97621 review ID's occur once, 764 occurss twice, 25 occurs three times.
- repeated reviewid values can be associated with multiple orders.
- 988673 unique orders represented in reviews table.
- 547 orders have multiple review records : 543 have 2 reviews, and 4 have three
- 'review score' ranges from 1 to 5.
- 5-star reviews are most common, followed by 4 star.
- review titles and messages have substantial missingness because written comments are optional
- no completely duplicated rows
- review metrics must be aggregated carefully at the apropriate business grain before being joined to other tables

In [98]:
geolocation = pd.read_csv(DATA_PATH + "olist_geolocation_dataset.csv")

In [100]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [101]:
geolocation.shape

(1000163, 5)

In [102]:
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [103]:
geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [105]:
geolocation.duplicated().value_counts().sort_index()

False    738332
True     261831
Name: count, dtype: int64

In [108]:
geolocation.duplicated().sum()

np.int64(261831)

In [109]:
geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [110]:
geolocation.groupby('geolocation_zip_code_prefix').size().describe()

count    19015.000000
mean        52.598633
std         72.057907
min          1.000000
25%         10.000000
50%         29.000000
75%         66.500000
max       1146.000000
dtype: float64

In [111]:
geolocation.groupby('geolocation_zip_code_prefix').size().value_counts().sort_index().head(20)

1     1043
2      642
3      518
4      434
5      427
6      396
7      357
8      344
9      339
10     280
11     298
12     299
13     317
14     292
15     259
16     247
17     225
18     284
19     288
20     248
Name: count, dtype: int64

In [112]:
geolocation[geolocation.duplicated(keep=False)].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP
10,1013,-23.547325,-46.634184,sao paulo,SP
13,1012,-23.548946,-46.634671,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
16,1039,-23.541883,-46.639919,sao paulo,SP
17,1024,-23.541390,-46.629899,são paulo,SP
18,1009,-23.546935,-46.636588,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP
21,1020,-23.552235,-46.628441,são paulo,SP
22,1011,-23.546690,-46.635447,são paulo,SP
24,1050,-23.549774,-46.645599,sao paulo,SP
25,1045,-23.541594,-46.641894,sao paulo,SP
27,1007,-23.550393,-46.637302,sao paulo,SP

In [113]:
geolocation[['geolocation_lat', 'geolocation_lng']].drop_duplicates().shape[0]

718463