In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [3]:
from src.config import RAW_DATA_DIR
from src.data_loader import load_csv

orders = load_csv('olist_orders_dataset.csv')
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [5]:
from src.cleaning import convert_datetime_columns

order_datetime_col = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

orders = convert_datetime_columns(orders, order_datetime_col)

In [6]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [8]:
order_items = load_csv('olist_order_items_dataset.csv')
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [9]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [10]:
items_datetime_col = ['shipping_limit_date']
order_items = convert_datetime_columns(order_items, items_datetime_col)

In [11]:
payments = load_csv('olist_order_payments_dataset.csv')
payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [12]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [13]:
customers = load_csv('olist_customers_dataset.csv')
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [14]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [15]:
geo = load_csv('olist_geolocation_dataset.csv')
geo.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [16]:
reviews = load_csv('olist_order_reviews_dataset.csv')
reviews.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [17]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [18]:
reviews_datetime_col = ['review_creation_date', 'review_answer_timestamp']
reviews = convert_datetime_columns(reviews, reviews_datetime_col)
reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [19]:
products = load_csv('olist_products_dataset.csv')
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [20]:
sellers = load_csv('olist_sellers_dataset.csv')
sellers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [21]:
category_name = load_csv('product_category_name_translation.csv')
category_name.dtypes

product_category_name            str
product_category_name_english    str
dtype: object

In [22]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [23]:
orders[orders['order_delivered_customer_date'].isna()][['order_status', 'order_delivered_customer_date']].head(20)

    order_status order_delivered_customer_date
6       invoiced                           NaT
44       shipped                           NaT
103     invoiced                           NaT
128   processing                           NaT
154      shipped                           NaT
162      shipped                           NaT
231      shipped                           NaT
266  unavailable                           NaT
299      shipped                           NaT
305      shipped                           NaT
324   processing                           NaT
333      shipped                           NaT
374      shipped                           NaT
397     canceled                           NaT
430      shipped                           NaT
444      shipped                           NaT
455     invoiced                           NaT
540      shipped                           NaT
583      shipped                           NaT
586  unavailable                           NaT

In [24]:
orders[
    (orders['order_status'] == 'delivered') & (orders['order_delivered_customer_date'].isna())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

## Orders 
- 160 missing approval timestamps
- 1783 missing carrier timestamps
- 2965 missing customer delivery timestamps
- 8 delivered orders have no customer-delivery timestamp

## Missing Delivery Date Analysis

Missing Delivery dates are expected for orders that have not reached the delivered stage.

however 8 orders have 'order_status = delivered' while 
'order_delivered_customer_date' is missing, these records are retained because the true delivery date is unknown but theu should be treated as data-quality issue exceptions.

In [25]:
orders[orders['order_approved_at'].isna()][['order_status', 'order_purchase_timestamp', 'order_approved_at']].head(20)

     order_status order_purchase_timestamp order_approved_at
1130     canceled      2018-08-28 15:26:39               NaT
1801     canceled      2018-09-20 13:54:16               NaT
1868     canceled      2017-03-04 12:14:30               NaT
2029     canceled      2018-08-29 16:27:49               NaT
2161     canceled      2017-05-01 16:12:39               NaT
3056     canceled      2016-10-04 19:41:32               NaT
3094     canceled      2018-08-21 10:25:18               NaT
3684     canceled      2018-08-07 16:33:59               NaT
4373     canceled      2018-08-09 14:54:47               NaT
4939     canceled      2018-08-22 18:52:29               NaT
5149     canceled      2018-09-13 09:56:12               NaT
5323    delivered      2017-02-18 14:40:00               NaT
5432     canceled      2018-08-28 08:18:22               NaT
5518     canceled      2018-08-18 12:39:31               NaT
5642     canceled      2017-01-13 11:06:56               NaT
6356     canceled      2018-08-09 10:55:10               NaT
7434      created      2017-12-05 01:07:52               NaT
7457     canceled      2018-08-15 11:05:44               NaT
8289     canceled      2017-05-10 11:52:51               NaT
9238      created      2018-02-09 17:21:04               NaT

### missing approval timestamp analysis

most missing 'order_apprved_at' values occur for cancelled or created orders, where an approval timestamp may legitimately not exist.

a small nnumber of delivered orders also have a missing approval timestamp, these records are retained because the true approval time is unknown, but they should be treated as data-quality exceptions.

In [26]:
orders[orders['order_delivered_carrier_date'].isna()][['order_status', 'order_purchase_timestamp', 'order_delivered_carrier_date']].head(20)

     order_status order_purchase_timestamp order_delivered_carrier_date
6        invoiced      2017-04-11 12:22:08                          NaT
103      invoiced      2018-08-03 17:44:42                          NaT
128    processing      2017-09-03 14:22:03                          NaT
266   unavailable      2017-11-16 15:09:28                          NaT
324    processing      2016-10-05 22:44:13                          NaT
397      canceled      2018-08-04 14:29:27                          NaT
455      invoiced      2017-08-01 18:17:41                          NaT
586   unavailable      2018-01-31 11:31:37                          NaT
687   unavailable      2017-08-14 17:38:02                          NaT
737   unavailable      2018-01-08 19:39:03                          NaT
741    processing      2017-11-24 20:09:33                          NaT
1130     canceled      2018-08-28 15:26:39                          NaT
1160  unavailable      2017-09-27 20:55:33                          NaT
1192   processing      2017-11-17 06:34:36                          NaT
1516   processing      2017-02-13 18:32:55                          NaT
1579  unavailable      2017-08-24 11:04:41                          NaT
1582   processing      2017-03-15 10:30:17                          NaT
1604   processing      2018-05-05 22:32:38                          NaT
1619   processing      2017-11-21 17:54:26                          NaT
1801     canceled      2018-09-20 13:54:16                          NaT

In [27]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

### Orders Data Cleaning Decision 

datetime columns converted to proper datetime types

missing delivery and approval timestamps looked on basis of order_status. missing timestamps are retained as NaT because they can represent legitimate stages of the order lifecycle.

data quality exceptions
- delivered orders with missing customer delivery date
- delivered orders with missing approval timestamp

these exceptions will be retained and handled as data-quality signals rather than being filled with artificial values

In [28]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [29]:
products[products['product_category_name'].isna()].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [30]:
products[products['product_category_name'].isna()][['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']].isna().all(axis=1).value_counts()

False    610
Name: count, dtype: int64

In [31]:
products[products['product_category_name'].isna()][['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']].isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64

In [32]:
products[products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [34]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [35]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [36]:
products["product_category_name"].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 73, dtype: int64

In [37]:
from src.config import PROCESSED_DATA_DIR

In [38]:
orders.to_csv(PROCESSED_DATA_DIR / 'orders_cleaned.csv', index=False)

In [39]:
(PROCESSED_DATA_DIR / 'orders_cleaned.csv').exists()

True

In [40]:
order_items.to_csv(PROCESSED_DATA_DIR / 'order_items_cleaned.csv', index=False)

In [41]:
(PROCESSED_DATA_DIR / 'order_items_cleaned.csv').exists()

True

In [42]:
payments.to_csv(PROCESSED_DATA_DIR / 'payments_cleaned.csv', index=False)

In [43]:
(PROCESSED_DATA_DIR / 'payments_cleaned.csv').exists()

True

In [44]:
products.to_csv(PROCESSED_DATA_DIR / 'products_cleaned.csv', index=False)

In [45]:
(PROCESSED_DATA_DIR / 'products_cleaned.csv').exists()

True

In [46]:
sellers.to_csv(PROCESSED_DATA_DIR / 'sellers_cleaned.csv', index=False)

In [47]:
(PROCESSED_DATA_DIR / 'sellers_cleaned.csv').exists()

True

In [48]:
customers.to_csv(PROCESSED_DATA_DIR / 'customers_cleaned.csv', index=False)

In [49]:
(PROCESSED_DATA_DIR / 'customers_cleaned.csv').exists()

True

In [50]:
reviews.to_csv(PROCESSED_DATA_DIR / 'reviews_cleaned.csv', index=False)

In [51]:
(PROCESSED_DATA_DIR / 'reviews_cleaned.csv').exists()

True

In [52]:
category_name.to_csv(PROCESSED_DATA_DIR / 'category_translation_cleaned.csv', index=False)

In [53]:
(PROCESSED_DATA_DIR / 'category_translation_cleaned.csv').exists()

True

In [54]:
geo = geo.drop_duplicates()

In [55]:
geo.shape

(738332, 5)

In [56]:
geo.duplicated().sum()

np.int64(0)

In [57]:
geo.to_csv(PROCESSED_DATA_DIR / 'geolocation_cleaned.csv', index=False)

In [58]:
(PROCESSED_DATA_DIR / 'geolocation_cleaned.csv').exists()

True

In [59]:
from pathlib import Path

list(PROCESSED_DATA_DIR.glob("*.csv"))

[WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/category_translation_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/customers_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/geolocation_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/orders_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/order_items_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/payments_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/products_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/reviews_cleaned.csv'),
 WindowsPath('C:/Users/Mrityunjai/OneDrive/Desktop/Anomaly-Agent-Project/data/processed/sellers_cleaned.csv')]

                                                                                    +-------------------+
                                                                                    |     CUSTOMERS     |
                                                                                    +-------------------+
                                                                                              |
                                                                                              |
                                                                                          CUSTOMER_ID
                                                                                              |
                                +----------+                                       +--------------------+
                                | PAYMENTS |                   <---------order_id  |     ORDERS         |
                                +----------+                                       |    1 row/order     |
                                                                                   +--------------------+
                                                                                             |
                                                                                             |
                                                                                             order_id
                                                                                             |
                                                                                             |
                                                                      --------------------------------------------------
                                                                      |                       |                        |
                                                                      |                       |                        |
                                                        +---------------+          +------------------+             +-----------------+
                                                        | ORDER_ITEMS   |          |     REVIEWS      |             |     PAYMENTS    |
                                                        +---------------+          +------------------+             +-----------------+
                                                               |
                                                               |
                                                               |
                                                    ---------------------
                                                    |                   |
                                                    |                   |
                                           +--------------+       +-------------+
                                           |  PRODUCTS    |       |  SELLERS    |
                                           +--------------+       +-------------+
                                                  |                     |
                                                  |                     |
                                                  |                     | ZIP
                                               category                 |
                                                  |                  GEOLOCATION
                                        CATEGORY TRANSLATION